### ISSUE TITLE
How to enlarge the timing interval b/w last Ack and 1st data in?

### ISSUE THREAD

**Issue by alec178** [eblot/pyftdi#100]
Hi Emmanuel,

I'm using pyftdi-0.28.8.
I would like to enlarge the timing interval b/w last Ack and 1st data in, within an I2C READ. (see below diagram, for example, make interval time 216us to 1ms)
How shall I configure `pyftdi`?

![2018-5-2 10-15-53](https://user-images.githubusercontent.com/32443068/39502491-20f5bf68-4df3-11e8-9928-8ae218a22469.jpg)

Alec

**Comment by eblot** [comment]
Well, it is a bit out-of-scope with the initial design, but I think I could add an API that would allow this kind of use case among others.

**Comment by eblot** [comment]
I've added a new boolean parameter to I2cPort method: start(=True)
If it is unset, PyFtdi will not emit a prolog (start + address) sequence.

Therefore you could write:

    from time import sleep

    # emit a START sequence is read address, but read no data and keep the bus busy
    port.read(0, relax=False)
    # wait for ~1ms (0.8ms + imprecise USB stack delay) 
    sleep(0.0008) 
    # read 4 bytes, without emitting the start sequence, and release the bus
    port.read(4, start=False)

Would it be ok?

See `i2c_opt_start` branch.

**Comment by alec178** [comment]
Sorry, I can't find any branch, which is named `i2c_opt_start `.

![2018-5-5 11-02-37](https://user-images.githubusercontent.com/32443068/39659117-fdc7e882-5053-11e8-9630-b8107d4fa651.jpg)

**Comment by eblot** [comment]
Sorry, I forgot to push it. Now it is.

**Comment by eblot** [comment]
`i2c_opt_start` has been merged into `master` branch as v0.29.0

**Comment by alec178** [comment]
It works, thanks!

**Comment by eblot** [comment]
Great, thanks for the feedback
