### ISSUE TITLE
Fails to install from pip on Ubuntu 16.04

### ISSUE THREAD

**Issue by the-moog** [eblot/pyftdi#105]
pip3 install pyftdi

installs pyusb and pyserial but fails with build error for pyftdi.

error: [Errno 2] No such file or directory: 'pyftdi/LICENSE'
Which is not present in the distro so no surprise.

installing from git clone using
sudo python3 setup.py install
works fine

**Comment by eblot** [comment]
Very true, I need to fix this.

**Comment by eblot** [comment]
Weird, I cannot reproduce this issue on Debian 9 (although pip complains about `bdist_wheel`). I' so tired of the `setuptools`...

**Comment by eblot** [comment]
Fix in 17dec41b (v0.29.2)
