### ISSUE TITLE
Missing introduction to jtag in API documentation

### ISSUE THREAD

**Issue by ljtjerry** [eblot/pyftdi#112]
I have an FTDI232H and I want to use it as a jtag port.
I searched the documentation site(http://eblot.github.io/pyftdi/api/index.html), but nothing related to jtag found.
I'm new to FTDI232H, could someone helps me about it or add some introduction about jtag port in that documentation? 

API documentation
ftdi - FTDI driver
gpio - GPIO API
i2c - I2C API
spi - SPI API
serialext - UART API
usbtools - USB tools
misc - Miscellaneous helpers

**Comment by eblot** [comment]
JTAG support is really basic (do not expect to use as a debugger), it has been design to perform boundary tests. 

You can find a very basic example in the `tests/` directory
