### ISSUE TITLE
Typo in gpio.py

### ISSUE THREAD

**Issue by snizzard** [eblot/pyftdi#113]
There seems to be a typo in `gpio.py` in the `set_direction` definition.

Here is the whole function:

`def set_direction(self, pins, direction):`
        `if direction > self.MASK:`
`raise GpioException("Invalid direction mask")`
 ` self._direction &= ~pins`
 `self._direction |= (pins & direction)`
 `self._ftdi.set_bitmode(self.direction, Ftdi.BITMODE_BITBANG)`

In that last part, the function changes the global variable `self._direction` but then passes the local variable `direction` to the function.  This seems odd...

Shouldn't it be passing the global `self._direction` with an underscore instead of `self.direction` ?

EDIT: sorry for all the edits and bad code formatting, I'm new to git comments lol

**Comment by eblot** [comment]
self.direction is a property that returns self._direction (see @ line ~55), so reading one or another value does the same, but I agree it would be cleaner to call the instance variable rather than the property, I'll change this.

Thanks for the report.

**Comment by eblot** [comment]
Done in 0a451f63
