### ISSUE TITLE
problem with i2c clockstretching

### ISSUE THREAD

**Issue by sbouge13a** [eblot/pyftdi#140]
I am reading a htu21d temperature/humidity sensor with a ft232h. The most significant bit of a read is always high. I checked on my scope, the signal shows the correct value being transmitted but the msb of a read is always high when pyftdi spits it out.

**Comment by sbouge13a** [comment]
The problem was actually with the htu21s temperature sensor, not pyftdi. It works just fine with a similar sensor.

**Comment by eblot** [comment]
Ok thanks for the feedback.
