### ISSUE TITLE
I2C Missing required positional arguments

### ISSUE THREAD

**Issue by pkissel** [eblot/pyftdi#151]
Hello,

I'm probably missing something simple but when I try the example code I'm getting missing positional arguments errors.

    from pyftdi.i2c import I2cController
    i2c = I2cController
    i2c.configure('ftdi:///1')

Which gives the error:

    i2c.configure('ftdi:///1')
    TypeError: configure() missing 1 required positional argument: 'url'

If I change this to

    from pyftdi.i2c import I2cController
    i2c = I2cController
    i2c.configure(url='ftdi:///1')

Then I get 

    i2c.configure(url='ftdi:///1')
    TypeError: configure() missing 1 required positional argument: 'self'

**Comment by eblot** [comment]
It is because you are trying to call configure on the class, not an instance of the class. Try

    i2c = I2cController()  # note the parenthesis

then either

    i2c.configure('ftdi:///1') 

or

    i2c.configure(url='ftdi:///1') 

See the examples in the [documentation](http://eblot.github.io/pyftdi/api/i2c.html#quickstart)

**Comment by pkissel** [comment]
Silly mistake.  That works, thank you!
