### ISSUE TITLE
Behaviour when enumerating the FTDI devices present

### ISSUE THREAD

**Issue by friedrichromstedt** [eblot/pyftdi#160]
When using:

    $ python3
    >>> from pyftdi.ftdi import Ftdi
    >>> Ftdi().open_from_url('ftdi:///?')

the Python interpreter exits immediately after printing the enumeration of the devices found. Is this intended?

**Comment by eblot** [comment]
Yes it is, at least for now.

**Comment by eblot** [comment]
I guess that an option to query the list without forcing the interpreter to exit would be helpful.

**Comment by eblot** [comment]
New API have been added to enumerate URLs w/o triggering a `SystemExit` exception in 7a111b234ee5686bd1aa15b33a84b306062036a5

**Comment by eblot** [comment]
Delivered as 50c95ac0ce2c148699be6495dfb278cae58917d2 (v0.46)
