### ISSUE TITLE
How to use CBUS pins on FT230X?

### ISSUE THREAD

**Issue by DaleMitchell** [eblot/pyftdi#175]
I'm not able to follow the obscure examples, need more verbose instructions. For example, how do you set CBUS0 high or low?

**Comment by eblot** [comment]
You cannot, see https://eblot.github.io/pyftdi/gpio.html#cbus-gpio and #174.

**Comment by eblot** [comment]
Now implemented and documented, see
https://eblot.github.io/pyftdi/gpio.html#cbus-gpio-access and 
https://eblot.github.io/pyftdi/eeprom.html#eeprom-cbus

**Comment by DaleMitchell** [comment]
Thanks!
