### ISSUE TITLE
PyPi is behind releases

### ISSUE THREAD

**Issue by newAM** [eblot/pyftdi#176]
The currently released version is 46.4, but PyPi is still at 44.2.  Can the current release be pushed to PyPi?

**Comment by eblot** [comment]
Yes, I know...

It is kinda done on "purpose" as github master is more a development environment, and I try to only push stable versions to PyPI. I'll push v0.47 soon.

**Comment by eblot** [comment]
v0.47.2 now available on [PyPi](https://pypi.org/project/pyftdi/0.47.2/).
