### ISSUE TITLE
_find_devices fails to find all devices on windows

### ISSUE THREAD

**Issue by FelixdeNeve** [eblot/pyftdi#177]
Hi,
Thanks for your work on this library. I'm currently working on a project that uses several FT4232H devices (all with blank EEPROMs) connected to the host PC running windows via a USB hub.
When I use the Ftdi.show_devices() only one of the devices is listed (each of the interfaces are given so it returns 4 URLS). In addition, because the program does not recognise that the other urls exist, I can only open the first device with the url (other devices can be opened as pyusb objects). Using a linux machine all of the devices are correctly listed. 
I found that replacing the _find_devices() function with usb.core.find() causes the program to behave as expected.

**Comment by eblot** [comment]
Can you provide some info about how you configured your devices under Windows? Even some screenshots of Zadig interfaces. Thanks.

**Comment by FelixdeNeve** [comment]
The devices were configured with Zadig such that the composite parents became LibUSB Win32 Devices.
Here's a zadig screenshot for the configured devices:
![zadig](https://user-images.githubusercontent.com/10976147/77053156-d1598480-69c5-11ea-9dd6-55ade3f69250.JPG)

**Comment by eblot** [comment]
Ok thanks.
I'll try to reproduce the problem (knowing  I deeply hate Windows...)

**Comment by FelixdeNeve** [comment]
Thanks very much!

**Comment by eblot** [comment]
Ok, I do not have two FT4232H available, but I found 2 FT232H with no EEPROMs.
On macOS, this gives:

    $ pyftdi/bin/ftdi_urls.py
    Available interfaces:
      ftdi://ftdi:2232:14:12/1   (Dual RS232-HS)
      ftdi://ftdi:2232:14:12/2   (Dual RS232-HS)
      ftdi://ftdi:2232:14:13/1   (Dual RS232-HS)
      ftdi://ftdi:2232:14:13/2   (Dual RS232-HS)

What does it show on Windows (while I upgrade the VM, Windows 10, ...)?

**Comment by FelixdeNeve** [comment]
This is similar to what I would get on Linux. On Windows I would expect it to show just: 
  ftdi://ftdi:2232:14:12/1   (Dual RS232-HS)
  ftdi://ftdi:2232:14:12/2   (Dual RS232-HS)

**Comment by eblot** [comment]
and what do you actually get?

**Comment by FelixdeNeve** [comment]
Here's what I get:

`from pyftdi.ftdi import Ftdi`
`Ftdi.show_devices()`
` Available interfaces:`
` ftdi://ftdi:4232:0:6/1   (Quad RS232-HS)`
` ftdi://ftdi:4232:0:6/2   (Quad RS232-HS)`
` ftdi://ftdi:4232:0:6/3   (Quad RS232-HS)`
` ftdi://ftdi:4232:0:6/4   (Quad RS232-HS)`

**Comment by eblot** [comment]
Ok, I think I found the culprit. Working to fix this.

**Comment by eblot** [comment]
c:\Users\eblot\AppData\Local\Programs\Python\Python37\Scripts>ftdi_urls.py
    Available interfaces:
      ftdi://ftdi:2232:0:1/1   (Dual RS232-HS)
      ftdi://ftdi:2232:0:1/2   (Dual RS232-HS)
      ftdi://ftdi:2232:0:2/1   (Dual RS232-HS)
      ftdi://ftdi:2232:0:2/2   (Dual RS232-HS)

**Comment by eblot** [comment]
It should be fixed. Please re-open with it still does not work with FT4232H
