### ISSUE TITLE
Initial argument not working.

### ISSUE THREAD

**Issue by natankeddem** [eblot/pyftdi#184]
Running v0.50.0 on a FT4232H. Standard read and write to all ports is working well.  I am trying to utilize configure with the initial argument but there is no effect.  The port always seems to configure to 0x00 no matter the value of initial.  The port does not change value until a discrete write_port call.

```
gpio = GpioAsyncController()
gpio.configure(url, direction = 0xFF, initial = 0xFF)
#port is 0x00 even though initial is 0xFF
gpio.write_port(0xFF)
#now the port is 0xFF
```

**Comment by eblot** [comment]
Very true, my mistake. Reproduced.
