### ISSUE TITLE
Can not write to eeprom on 4232h

### ISSUE THREAD

**Issue by Renha** [eblot/pyftdi#191]
Could not write to empty eeprom on 4232h, always get the error and nothing is written.
Checked versions 0.49.0 and 0.51.2.

**Comment by eblot** [comment]
Could you provide some details?

- what API or command did you use and how,
- what error message did you get, if any
- have you tried with another device?
- anything useful that can help understand and reproduce the issue, as “it does not work” is a bit difficult to troubleshoot :-)

Thanks.

**Comment by Renha** [comment]
Hey! There's chance of the problems on the schematics, I'll update the case accordingly when it will be confirmed or not.

**Comment by eblot** [comment]
Any news?

**Comment by Renha** [comment]
Oh, sorry! That was hardware issue! Thank you

**Comment by eblot** [comment]
Thanks for the feedback.
