### ISSUE TITLE
JTAG shift_register does not work

### ISSUE THREAD

**Issue by markmelvin** [eblot/pyftdi#194]
I am trying to use pyFTDI with JTAG and I believe the current version of JtagEngine is broken.  

Simple writes and reads with `write_ir` and `read_dr` do seem to work but I want to write bits to TDI while reading bits off TDO, so I am using `shift_register`.  There seems to be a couple issues:

1) Simply using `JtagEngine.shift_register` doesn't work at all because it doesn't pass through the `use_last` argument so there is no way to specify this so that TMS transitions on the last bit. Thus, as far as I see it - you end up sending one bit too many - which causes data problems going out.
2) Using `JtagEngine.jtag.shift_register()` I can pass the argument `use_last`, which appears to properly transition the TAP state machine aligned with the data, but it ends up not shifting the data properly coming off the JTAG TDO pin as the last data bit is sent in unison with the TMS signal set to 1 bit the last incoming bit is never read - thus the incoming data is wrong.

Am I using this incorrectly?  It seems the simultaneously reading and writing is broken.

**Comment by eblot** [comment]
Unfortunately I have used JTAG for nearly 10 years, so it may be broken.

I've wondered several times whether I should remove its support from `pyftdi`... Patches are always welcome - see other tickets related to JTAG if it may help.

Sorry about that.

**Comment by markmelvin** [comment]
I have a working solution that I can turn into a patch this week. I wouldn't remove it. It is a clever implementation!

**Comment by eblot** [comment]
Great, and thanks.

**Comment by eblot** [comment]
Please create a PR if you have a fix for this issue. Thanks

**Comment by markmelvin** [comment]
Look up. I already did...

**Comment by eblot** [comment]
> Look up. I already did...
Very sorry, I missed it.

**Comment by eblot** [comment]
Merged. Thanks for the investigation and the patch. Sorry for the delay.
