### ISSUE TITLE
Stop violates I2C timing

### ISSUE THREAD

**Issue by DPM-PMC** [eblot/pyftdi#205]
Current design has data idle high until stop is sent.  When stop is sent CLK immediately goes high and SDA immediately goes low.  However, SDA should not change until after the stop hold time timing spec.
![image](https://user-images.githubusercontent.com/67423401/85727124-60102880-b6bc-11ea-8fb5-daaa167e883c.png)
Most parts this does not appear to be an issue.  However, the NXP PCA9848 I2C switch will not recognize it as a stop.

Recommend changing _stop() to start with a _clk_lo_data_lo to ensure that SDA is low before posedge of CLK.
![image](https://user-images.githubusercontent.com/67423401/85727585-c2692900-b6bc-11ea-9703-ef1254350323.png)

This ensures SDA is low for the full stop_setup period.
![image](https://user-images.githubusercontent.com/67423401/85728111-39062680-b6bd-11ea-97d8-4d082137bed6.png)

**Comment by eblot** [comment]
I think it is a dup of #179.  
Unfortunately I lack time at the moment to create an I2C setup and reproduce this, but it is a major issue to address, I agree.

**Comment by naushir** [comment]
I've run into exactly the same issue with a TCA9548A I2C switch device attached to a FTDI2232H.

The above change has fixed the SDA transition violation for me as well.  @eblot, would you like me to create a PR for this fix?

**Comment by eblot** [comment]
Yes please do. I really have not time to work on PyFtdi at the moment, but this issue needs to be addressed. Thanks.

**Comment by naushir** [comment]
> @naushir Yes please do. I really have not time to work on PyFtdi at the moment, but this issue needs to be addressed. Thanks.

Done.  See PR https://github.com/eblot/pyftdi/pull/217

**Comment by daveismith** [comment]
We were seeing the same issue on some boards with a MCP23017, though strangely only one of them since we've got two on board. I'm guessing it's because of trace length. As soon as we applied this fix, the device started to work reliably.
