### ISSUE TITLE
i cant find vend id on my ft232h 

### ISSUE THREAD

**Issue by glennford49** [eblot/pyftdi#207]
device : adafruit ft232h
running on ubuntu:
from pyftdi.ftdi import Ftdi
Ftdi.show_devices()
Available interfaces:
  ftdi://ftdi:232h:1/1   (￿￿￿￿￿￿) # no ids on this field

**Comment by eblot** [comment]
This means you have no EEPROM attached or the EEPROM content is corrupted.
If there is an EEPROM, you need to program it, but I think the Adafruit is a "low cost" board (although 3x more expensive than similar chinese ones) with no EEPROM.

What is missing here is the description string, not the vendor id. The vendor id is `0x0403`, i.e. FTDI.
