### ISSUE TITLE
pyftdi.ftdi.FtdiError: UsbError: [Errno 16] Resource busy

### ISSUE THREAD

**Issue by glennford49** [eblot/pyftdi#208]
Error when running 2 python interpreter, first.py is for setting high of pin, when  second.py running on different python interpreter for reading pin state, it throws an error,  is there any way to run this 2 python files with my ftdi adapter? Device is ft232h

**Comment by mpratt14** [comment]
the FT232h only has 1 virtual interface. What you're suggesting is much more difficult than simply combining the two python files.

**Comment by glennford49** [comment]
Any device you can suggest that has virtual interface greater than 1 ?

**Comment by mpratt14** [comment]
See in the docs:
https://eblot.github.io/pyftdi/urlscheme.html

interface: the interface of FTDI device, starting from 1

1 for 230x and 232* devices,

1 or 2 for 2232* devices,

1, 2, 3 or 4 for 4232* devices

**Comment by glennford49** [comment]
Thanks
