### ISSUE TITLE
Gpio pins reset on close()

### ISSUE THREAD

**Issue by galen-elfert** [eblot/pyftdi#219]
When I close the GPIO device, all the pins go high, regardless of their last state. Is there any way to preserve the pin direction and settings setting after closing the device? This is an FT4232H.

**Comment by eblot** [comment]
See also #218.

I think I need to provide an option to explicitly leave the port in its last state on closure.

**Comment by eblot** [comment]
This has been implemented in 3aafecb and 18370d5. It will be part of v0.53.
