### ISSUE TITLE
double import

### ISSUE THREAD

**Issue by anders-code** [eblot/pyftdi#24]
Why does pyftdi have two layers of directories named pyftdi and require things like "from pyftdi.pyftdi import ..."?
This seems unusual to me in the world of python packages. I don't know of another example like it.
If its something for a good reason and not to be fixed, it might make sense to explain in the README or FAQ.
Notwithstanding, this is a very useful little project and I greatly appreciate it. Thanks, Emmanuel!!!

**Comment by eblot** [comment]
Merged as  a3ca2ae. Thanks!
