### ISSUE TITLE
Version checking cannot handle beta pyserial version string 

### ISSUE THREAD

**Issue by ahonkan-wing** [eblot/pyftdi#249]
https://github.com/eblot/pyftdi/blob/0b6797a68fb65a7191933ad40331af7edd54412a/pyftdi/bin/pyterm.py#L226

Current latest beta release is 3.5b0 which causes a
'''
    version = tuple([int(x) for x in serialver.split('.')])
ValueError: invalid literal for int() with base 10: '5b0'

'''

I got this from a pip3 install pyserial.  
You may add readme verbage to only pip3 install non-beta pyserial but it's probably better to fix the version checking

**Comment by eblot** [comment]
This is weird that a beta package is installed, but anyway, this was a bug.
Thanks for the report.
