### ISSUE TITLE
BITMODE_MASK has wrong value

### ISSUE THREAD

**Issue by LongHairedHacker** [eblot/pyftdi#26]
Hi,

I've noticed today that your Fdti.set_bitmode method does not work for cbus bitbang on a FT230XS.
The root of the problem seem to be a wrong value for Ftdi.BITMODE_MASK, since Ftdi.BITMODE_MASK & Ftdi.BITMODE_CBUS = 0x00, which is unfortunately the same Ftdi.BITMODE_RESET.

I'd suggest using 0x7F as mask instead.

**Comment by eblot** [comment]
Merged in 0b0a05733
