### ISSUE TITLE
Does pyftdi support the MCP2221 chips?

### ISSUE THREAD

**Issue by ullix** [eblot/pyftdi#287]
I used the pyftdi lib on an Adafruit FT232H Breakout board. I liked the lib very much, but the FT232H performance was lousy! I've posted a review here: [Review of USB-To-I2C Dongles as used by GeigerLog](https://sourceforge.net/projects/geigerlog/files/Articles/Review%20of%20USB-To-I2C%20Dongles%20as%20used%20by%20GeigerLog-v1.0.pdf/download)

Now I was pointed to [another breakout board using chip MCP2221A](https://www.adafruit.com/product/4471), also used as USB-To-I2C dongle. As the FTDI232H and the MCP2221 seem to have a lot in common I was wondering whether pyftdi is also supporting this chip?

**Comment by eblot** [comment]
No sorry. PyFTDI only deals with FTDI protocol(s).

Yes, I2C support is quite lousy because the I2C ACK is performed by the host, so most of the time, it requires a full round trip over USB.
