### ISSUE TITLE
only first 8 gpio pins

### ISSUE THREAD

**Issue by quantrpeter** [eblot/pyftdi#299]
Hi
    my ft2232hl board has 32 gpio, but i can only control the first 8 pins

gpio.set_gpio(7, True)

because the parameter is byte only. Any hints?
thanks
Peter

**Comment by eblot** [comment]
Technically, a FT2232 contains 2 16-bit GPIO port, not a single 32-bit GPIO port.
PyFtdi does not have a `set_gpio` API.
Please use the discussions to ask for support/question, issues are reserved for, well, issues :)

**Comment by quantrpeter** [comment]
thanks
