### ISSUE TITLE
I don't understand how to blink the RX or TX leds on the FT232

### ISSUE THREAD

**Issue by Zibri** [eblot/pyftdi#303]
If I operatore on GPIOS directly, there is not led activity.
How can I manually blink the leds?

```
from pyftdi import gpio
g = gpio.GpioAsyncController()
g.open_from_url("ftdi:///1")
f = g.ftdi
[missing blinking code here]
```

**Comment by eblot** [comment]
Please use the [discussion](https://github.com/eblot/pyftdi/discussions) for support about how to use PyFtdi. Issues are for bugs and enhancement requests, nor for support.

You'll also need to document:
1- the version of PyFtdi you are using
2- the board you are using (there is no led on a FTDI device, so the information about how a LED is connected to a FTDI is required)
