### ISSUE TITLE
pyftdi not acquiring serial num/id from FTDI dongle on Ubuntu

### ISSUE THREAD

**Issue by insane-dreamer** [eblot/pyftdi#332]
We have a FTDI USB dongle for a biosignal device that registers with the OS USB kernel, and shows up when listing devices with pyftdi, but doesn't return the serial num or any other info. This is on Ubuntu 21.10 with the latest pyftdi release. 

Here's what the syslog shows when plogging in the device: 
![usb-read](https://user-images.githubusercontent.com/25834/215188266-d3f70593-ef78-4336-a8ed-ac871061b23a.png)

But when querying with pyftdi: 
![pyftdi-img](https://user-images.githubusercontent.com/25834/215188887-332dbdb0-fff3-4d0f-862e-3865cd6ad661.png)

The same FTDI dongle works as expected with the FDTI official DLLs on Windows. However, using the FTDI .so for Linux + the ftd2xx python library yields the same results as with pyftdi, so whatever the issue is, neither library is picking up the dongle. 

Any idea of the cause, or way to work around it? Thanks.

**Comment by eblot** [comment]
Have you checked [this error message](https://eblot.github.io/pyftdi/troubleshooting.html#error-the-device-has-no-langid) against the troubleshooting guide?

**Comment by insane-dreamer** [comment]
That resolved it. Thanks!
