### ISSUE TITLE
<feature request - spi.py> allow the host to write zero bytes before read.

### ISSUE THREAD

**Issue by BrettRD** [eblot/pyftdi#35]
It would be handy for embedded development to be able to write:
`response =  spiport.exchange([], 10)`
to send nothing, and read ten bytes.

support for full duplex would be even better.

**Comment by eblot** [comment]
I'll have a look at this, hopefully next week.

**Comment by eblot** [comment]
Should be implemented with 98f66856. Let me know if there is an issue.

Tested with pyspiflash 0.4.1
