### ISSUE TITLE
Getting-started help (pyftdi on Windows 10 using Python 3.1.13 and single FTDI232H module)

### ISSUE THREAD

**Issue by wb0gaz** [eblot/pyftdi#389]
I am beginning work with pyftdi version 0.55.3 (on Windows 10, under Python 3.13.0, with a single FDT232H module attached). My (small) initial test program listing is below, and the printed text from the progrm follows. There are two concerns - about `open_from_url()` return value, and ftdiEeprom API.

Some initial steps are working - `Ftdi.show_devices()` and `Ftdi.list_devices()`, but I am not sure about result from `open_from_url()`, and initial attempt to dump EEPROM cannot start.

Question - `open_from_url()` is returning "none". Is this correct? 
I am following "ftdi - FTDI low-level driver".

Question - what is cause of the error "_NameError: name 'ftdiEeprom' is not defined_" when I try to inspect data in EEPROM? 
I am following documentation section "eeprom - EEPROM API Quickstart".

I have installed pyftdi and used Zadeg to create the required libusb-win32 device driver interface.

Below is my test program. Following that is the output I have obtained.

```py
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print("executing: import pyftdi")
import pyftdi
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print("executing: from pyftdi.ftdi import Ftdi")
from pyftdi.ftdi import Ftdi
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print ("executing: Ftdi.show_devices()")
print ("result:")
print(Ftdi.show_devices())
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print ("executing: Ftdi.list_devices()")
print ("result:")
print(Ftdi.list_devices())
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print("documentation section: ftdi - FTDI low-level driver")
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print ("executing: interface = Ftdi().open_from_url('ftdi:///1')")
print ("result:")
interface = Ftdi().open_from_url('ftdi:///1')
print("interface = ", interface)
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print("documentation section: eeprom - EEPROM API Quickstart")
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print ("executing: eeprom = ftdiEeprom()")
print ("result:")
eeprom = ftdiEeprom()
print("eeprom = ", eeprom)
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print("executing: eeprom.open('ftdi://ftdi:2232h/1')")
print ("result:")
eeprom.open('ftdi://ftdi:2232h/1')
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
print("executing: eeprom.dump_config()")
print ("result:")
eeprom.dump_config()
print("- - - - - - - - - - - - - - - - - - - - - - - - - - - -")
```

Below is the output of the program above, terminating in an error when I try to access eeprom:

```
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
executing: import pyftdi
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
executing: from pyftdi.ftdi import Ftdi
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
executing: Ftdi.show_devices()
result:
Available interfaces:
  ftdi://ftdi:232h:0:1/1  (Single RS232-HS)

None
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
executing: Ftdi.list_devices()
result:
[(UsbDeviceDescriptor(vid=1027, pid=24596, bus=0, address=1, sn=None, index=None, description='Single RS232-HS'), 1)]
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
documentation section: ftdi - FTDI low-level driver
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
executing: interface = Ftdi().open_from_url('ftdi:///1')
result:
interface =  None
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
documentation section: eeprom - EEPROM API Quickstart
- - - - - - - - - - - - - - - - - - - - - - - - - - - -
executing: eeprom = ftdiEeprom()
result:
Traceback (most recent call last):
  File "C:\Users\user\Desktop\pantilt\a.py", line 27, in <module>
    eeprom = ftdiEeprom()
             ^^^^^^^^^^
NameError: name 'ftdiEeprom' is not defined
```

**Comment by juanitoetc** [comment]
> Question - open_from_url() is returning "none". Is this correct?
I am following "ftdi - FTDI low-level driver".

No, that is not correct. I dont use Windows but I assume you are able to communicate with the device because it answers `Ftdi.show_devices()`. Your problem is that you are trying to use a class method when the API says it is a instance method.
Simple replace `interface = Ftdi().open_from_url('ftdi:///1')`
with
`ftdi = Ftdi()`
`interface = ftdi.open_from_url('ftdi:///1')`

> Question - what is cause of the error "NameError: name 'ftdiEeprom' is not defined" when I try to inspect data in EEPROM?
I am following documentation section "eeprom - EEPROM API Quickstart".

You are not importing the module needed. Add the line `from pyftdi.eeprom import FtdiEeprom` after `from pyftdi.ftdi import Ftdi`

**Comment by eabase** [comment]
@wb0gaz 
Please enclose your input, output and files in tripple back quotes, like this:
\`\`\`python
...
\<your code or output\>
...
\`\`\`

**Comment by eblot** [comment]
> @wb0gaz Please enclose your input, output and files in tripple back quotes

I've edited the original post, hope this improves readability. Thanks @wb0gaz

**Comment by eabase** [comment]
@eblot 
BTW. In Python you can print repeated characters with multipliers like this: `print('-'*40)`.

**Comment by wb0gaz** [comment]
Thank you for posting additional detail - 

The problems I encountered at first with pyftdi were purely due to my relative inexperience with Python, particularly use in object oriented fashion (I am basically embedded C/Assembly programmer). I was also not aware that text of posting to github page would be interpreted with Python language elements for mark-up, so again I appreciate the advice/guidance. I may return for advice on specifics of pyftdi, but for now I am able to use pyftdi at beginner level and am not currently experiencing any problem.     On Wednesday, November 20, 2024 at 07:42:16 AM MST, eabase ***@***.***> wrote:  
 
 


@eblot
BTW. In Python you can print repeated characters with multipliers like this: print('-'*40).

**Comment by wb0gaz** [comment]
As this was never a problem with pyftdi, only my inexperience with Python, I am closing this issue. If closing the issue is not correct step now, please let me know or adjust this posting as you see fit. Thank you again for the excellent support!
