### ISSUE TITLE
Typo in ftdi.py

### ISSUE THREAD

**Issue by andyfinity** [eblot/pyftdi#39]
[Line 387 in `ftdi.py`](https://github.com/eblot/pyftdi/blob/master/pyftdi/ftdi.py#L387) currently says:

        def open_bitband_from_url(...

It should probably say:

        def open_bitbang_from_url(...

**Comment by eblot** [comment]
Very true, I have not tested GPIO mode for a while... Fix will be part of v0.21.2

Thanks for the report.

**Comment by eblot** [comment]
Committed in 6c122c17a9
