### ISSUE TITLE
Forum for pyftdi?

### ISSUE THREAD

**Issue by cioma** [eblot/pyftdi#45]
Apologies for off-topic but is there a forum for pyftdi?

**Comment by eblot** [comment]
Not that I know about, you are the first to ask :-)

**Comment by rdpoor** [comment]
+1.  

For now, I've posted question / issue on StackOverflow.  

I have created a `pyftdi` tag and posted a question to https://stackoverflow.com/questions/48253119/pyftdi-finds-device-under-os-x-but-not-windows

**Comment by eblot** [comment]
Long shot but Discussions are now available on GitHub. Closing this ticket as Discussions should fit this need.
